# Generated by Django 5.0.1 on 2024-03-14 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Des",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=200)),
                ("titulo", models.CharField(blank=True, max_length=200)),
                ("descripcion", models.TextField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("fase", models.CharField(blank=True, max_length=100)),
                ("subfase", models.CharField(blank=True, max_length=100)),
                (
                    "procentaje",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "dependencias",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("observaciones", models.TextField()),
                (
                    "tiempo_estimado",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Tiempo Estimado (horas)"
                    ),
                ),
                (
                    "tiempo_real",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Tiempo real (horas)"
                    ),
                ),
                ("docu", models.BooleanField(blank=True, default=False, null=True)),
                ("completada", models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FaseDes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grupo", models.CharField(max_length=100)),
                ("cluster", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SubFaseDes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                ("fecha_inicio_planeada", models.DateField(blank=True, null=True)),
                ("fecha_inicio_real", models.DateField(blank=True, null=True)),
                (
                    "fecha_finalizacion_planeada",
                    models.DateField(blank=True, null=True),
                ),
                ("fecha_finalizacion_real", models.DateField(blank=True, null=True)),
                ("alcance", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("suspendido", "Suspendido"),
                            ("cerrado", "Cerrado"),
                        ],
                        max_length=50,
                    ),
                ),
                ("porcentaje_completado", models.IntegerField(default=0)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("abierto", "Proyectos Integración"),
                            ("suspendido", "Necesidades entrega operación"),
                            ("desarollo", "Proyectos Producto Propio"),
                            ("cerrado", "Cerrado"),
                        ],
                        max_length=50,
                    ),
                ),
                ("lider", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("I", "Tipo I"),
                            ("II", "Tipo II"),
                            ("III", "Tipo III"),
                            ("IV", "Tipo IV"),
                        ],
                        max_length=100,
                    ),
                ),
                ("antecedentes", models.TextField()),
                (
                    "fase",
                    models.CharField(
                        choices=[
                            ("inicio", "Inicio"),
                            ("planeacion", "Planeación"),
                            ("ejecucion", "Ejecución"),
                            ("monitoreo_control", "Monitoreo y Control"),
                            ("cierre", "Cierre"),
                        ],
                        max_length=100,
                    ),
                ),
                ("programas", models.CharField(max_length=100)),
                ("comentarios", models.TextField(blank=True, null=True)),
                ("spi", models.FloatField(default=0)),
                ("es", models.FloatField(default=0)),
                ("columna", models.BooleanField(default=False)),
                (
                    "grupo",
                    models.ManyToManyField(related_name="proyectos", to="gestor.grupo"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatrizRiesgo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("causas", models.TextField()),
                ("plan", models.TextField()),
                ("consecuencias", models.TextField()),
                ("descripcion_tiempo", models.TextField()),
                ("descripcion_alcance", models.TextField()),
                ("descripcion_costo", models.TextField()),
                (
                    "probavilidad",
                    models.IntegerField(
                        choices=[
                            (1, "Muy Bajo"),
                            (2, "Bajo"),
                            (3, "Medio"),
                            (4, "Alto"),
                            (5, "Muy Alto"),
                        ]
                    ),
                ),
                (
                    "gravedad",
                    models.IntegerField(
                        choices=[
                            (1, "Muy Bajo"),
                            (2, "Bajo"),
                            (3, "Medio"),
                            (4, "Alto"),
                            (5, "Muy Alto"),
                        ]
                    ),
                ),
                (
                    "riesgo",
                    models.CharField(
                        choices=[
                            ("grave", "Muy grave"),
                            ("importante", "Importante"),
                            ("apreciable", "Apreciable"),
                            ("marginal", "Marginal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("materializo", models.TextField()),
                ("acciones_mitigacion", models.TextField()),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestor.proyecto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Documentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descriocion", models.TextField()),
                ("link", models.URLField()),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestor.proyecto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Costos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contrato", models.CharField(max_length=100)),
                ("objeto", models.TextField()),
                ("tipo", models.CharField(max_length=100)),
                ("aliado", models.CharField(max_length=200)),
                ("contrato_aliado", models.CharField(max_length=100)),
                ("backlog", models.TextField()),
                ("one_time", models.TextField()),
                ("recurrente", models.TextField()),
                ("meses", models.CharField(max_length=100)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestor.proyecto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComentarioTarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificando_problema", models.TextField(blank=True)),
                ("causa", models.TextField(blank=True)),
                ("solucion", models.TextField(blank=True)),
                ("planes_mejora_aplicados", models.TextField(blank=True)),
                ("resultados_planes_mejora", models.TextField(blank=True)),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestor.proyecto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tablero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "proyect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tablero",
                        to="gestor.proyecto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Columna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tablero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columnas",
                        to="gestor.tablero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tarjeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("tipo", models.CharField(blank=True, max_length=100)),
                ("fecha_inicio", models.DateField(blank=True)),
                ("fecha_fin", models.DateField(blank=True)),
                ("porcentaje", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "columna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarjetas",
                        to="gestor.columna",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestor.proyecto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("archivo", models.FileField(upload_to="recursos")),
                (
                    "tarjeta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gestor.tarjeta"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("administrador", "Administrador"),
                            ("gerente", "Gerente"),
                            ("miembro", "Miembro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "equipos",
                    models.ManyToManyField(related_name="miembros", to="gestor.equipo"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("estado", models.CharField(max_length=100)),
                (
                    "procentaje",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("dependencias", models.ManyToManyField(blank=True, to="gestor.tarea")),
                (
                    "hito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gestor.tarjeta"
                    ),
                ),
                (
                    "asignado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gestor.usuario"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="proyecto",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gestor.usuario"
            ),
        ),
        migrations.CreateModel(
            name="Hito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("porcentaje", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestor.proyecto",
                    ),
                ),
                (
                    "asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestor.usuario",
                    ),
                ),
            ],
        ),
    ]
