# Generated by Django 5.0 on 2024-03-05 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrizriesgo',
            name='gravedad',
            field=models.CharField(choices=[('alto1', 'Alto'), ('medio', 'Medio'), ('Bajo2', 'Muy Bajo'), ('bajo1', 'Bajo'), ('alto2', 'Muy Alto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='matrizriesgo',
            name='probavilidad',
            field=models.CharField(choices=[('alto1', 'Alto'), ('medio', 'Medio'), ('Bajo2', 'Muy Bajo'), ('bajo1', 'Bajo'), ('alto2', 'Muy Alto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='proyect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros', to='gestor.proyecto'),
        ),
    ]
