# Generated by Django 5.0.1 on 2024-03-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestor", "0002_alter_comentariotarea_causa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentariotarea",
            name="fecha_creacion",
            field=models.DateField(),
        ),
    ]
