# Generated by Django 5.0.1 on 2024-03-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestor", "0003_alter_comentariotarea_fecha_creacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matrizriesgo",
            name="riesgo",
            field=models.CharField(max_length=20),
        ),
    ]
