# Generated by Django 5.0.1 on 2024-03-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestor", "0004_alter_matrizriesgo_riesgo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="fecha_creacion",
            field=models.DateField(),
        ),
    ]
