# Generated by Django 5.0.1 on 2024-03-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestor", "0005_alter_proyecto_fecha_creacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="fecha_creacion",
            field=models.DateField(blank=True, null=True),
        ),
    ]
