# Generated by Django 5.0.1 on 2024-03-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestor", "0006_alter_proyecto_fecha_creacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proyecto",
            name="grupo",
        ),
        migrations.AddField(
            model_name="proyecto",
            name="grupo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
