# Generated by Django 5.0.1 on 2024-03-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestor", "0013_rename_aliado_costos_cliente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="costos",
            name="bloqueo",
            field=models.BooleanField(default=False),
        ),
    ]
