# Generated by Django 5.0.1 on 2024-03-21 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestor", "0015_costoscostos_costosingresos_delete_fasedes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="cliente",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="contrato",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="name_contractor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="objeto",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="valor",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
    ]
